ALTER TYPE "ProcurementBidStatus" ADD VALUE IF NOT EXISTS 'TECHNICAL_EVALUATION_COMPLETED';
ALTER TYPE "ProcurementBidStatus" ADD VALUE IF NOT EXISTS 'L1_GENERATED';
ALTER TYPE "ProcurementBidStatus" ADD VALUE IF NOT EXISTS 'AWARD_RECOMMENDED';

ALTER TYPE "ProcurementLifecycleStage" ADD VALUE IF NOT EXISTS 'TECHNICAL_EVALUATION_COMPLETED';
ALTER TYPE "ProcurementLifecycleStage" ADD VALUE IF NOT EXISTS 'L1_GENERATED';
ALTER TYPE "ProcurementLifecycleStage" ADD VALUE IF NOT EXISTS 'AWARD_RECOMMENDED';

ALTER TYPE "ProcurementFinalStatus" ADD VALUE IF NOT EXISTS 'L4';

ALTER TYPE "ProcurementSubmissionStatus" ADD VALUE IF NOT EXISTS 'TECHNICAL_DOCUMENTS_UPLOADED';
ALTER TYPE "ProcurementSubmissionStatus" ADD VALUE IF NOT EXISTS 'FINANCIAL_QUOTE_UPLOADED';
ALTER TYPE "ProcurementSubmissionStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
